CREATE TABLE SQLMAP (
    KEY_ VARCHAR(100) PRIMARY KEY,
    SQL_ VARCHAR(100) NOT NULL
)

INSERT INTO SQLMAP(KEY_, SQL_) VALUES ('KEY1', 'SQL1');
INSERT INTO SQLMAP(KEY_, SQL_) VALUES ('KEY2', 'SQL2');